package br.com.Avaliacao_Eduardo_Dourado.view;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import br.com.Avaliacao_Eduardo_Dourado.dto.LutadorDTO;
import br.com.Avaliacao_Eduardo_Dourado.dto.LutaDTO;
import br.com.Avaliacao_Eduardo_Dourado.ctr.LutadorCTR;
import br.com.Avaliacao_Eduardo_Dourado.ctr.LutaCTR;
        

public class LutaVIEW extends javax.swing.JInternalFrame {

    LutadorDTO lutadorDTO = new LutadorDTO();
    LutadorCTR lutadorCTR = new LutadorCTR();
    LutaDTO lutaDTO = new LutaDTO();
    LutaCTR lutaCTR = new LutaCTR();
    
    int gravar_alterar;
    
    ResultSet rs;
    DefaultTableModel model_jtl_consultar_combate;
    DefaultTableModel model_jtl_consultar_lutador;
    
        
    /**
     * Creates new form ProdutoVIEW
     */
    public LutaVIEW() {
        initComponents();

        model_jtl_consultar_lutador = (DefaultTableModel) jtl_consultar_lutador.getModel();
        model_jtl_consultar_combate = (DefaultTableModel) jtl_consultar_combate.getModel();

        jtl_consultar_lutador.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
         
        jtl_consultar_lutador.setRowSelectionAllowed(true);
        jtl_consultar_lutador.setColumnSelectionAllowed(false);


        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome_combate = new javax.swing.JTextField();
        cod_combate = new javax.swing.JTextField();
        custo_aposta_combate = new javax.swing.JTextField();
        pesquisa_nome_lutador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_consultar_lutador = new javax.swing.JTable();
        btnPesquisarLutador = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtl_consultar_combate = new javax.swing.JTable();
        pesquisa_nome_combate = new javax.swing.JTextField();
        brnPesquisarCombate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        nome_combate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_combateActionPerformed(evt);
            }
        });

        pesquisa_nome_lutador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_nome_lutadorActionPerformed(evt);
            }
        });

        jtl_consultar_lutador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jtl_consultar_lutador);

        btnPesquisarLutador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/pesquisar.png"))); // NOI18N
        btnPesquisarLutador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLutadorActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jtl_consultar_combate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jtl_consultar_combate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_consultar_combateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtl_consultar_combate);

        pesquisa_nome_combate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_nome_combateActionPerformed(evt);
            }
        });

        brnPesquisarCombate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Avaliacao_Eduardo_Dourado/view/imagens/pesquisar.png"))); // NOI18N
        brnPesquisarCombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnPesquisarCombateActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Código");

        jLabel4.setText("Val. Aposta");

        jLabel6.setText("Nome:");

        jLabel7.setText("Lutador:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Luta");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisa_nome_combate, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnPesquisarCombate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nome_combate)
                                            .addComponent(cod_combate)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(custo_aposta_combate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(173, 173, 173))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pesquisa_nome_lutador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPesquisarLutador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnNovo)
                                                .addGap(79, 79, 79)
                                                .addComponent(btnSalvar)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(254, 254, 254)
                                        .addComponent(jLabel9))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(btnCancelar)
                                .addGap(83, 83, 83)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jLabel8)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brnPesquisarCombate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pesquisa_nome_combate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nome_combate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cod_combate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(custo_aposta_combate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pesquisa_nome_lutador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnPesquisarLutador)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_combateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_combateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_combateActionPerformed

    private void pesquisa_nome_combateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_nome_combateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_nome_combateActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        liberaCampos(true);
        liberaBotoes(false, true, true, false, true);
        gravar_alterar = 1;// TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarLutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLutadorActionPerformed
        preencheTabelaLutador(pesquisa_nome_lutador.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarLutadorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(gravar_alterar==1){
            gravar();
            gravar_alterar=0;
        }
        else{
            if(gravar_alterar==2){
                alterar();
                gravar_alterar=0;
            }
            else{
                JOptionPane.showMessageDialog(null, "erro no sistema!!!");
            }
        }
        
        limpaCampos();
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void brnPesquisarCombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnPesquisarCombateActionPerformed
        preencheTabelaCombate(pesquisa_nome_combate.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_brnPesquisarCombateActionPerformed

    private void jtl_consultar_combateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_consultar_combateMouseClicked
        preencheCamposCombate(Integer.parseInt(String.valueOf(
        jtl_consultar_combate.getValueAt(
        jtl_consultar_combate.getSelectedRow(), 0))));
        liberaBotoes(false, true, true, true, true);// TODO add your handling code here:
    }//GEN-LAST:event_jtl_consultar_combateMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
        limpaCampos();
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
        model_jtl_consultar_combate.setNumRows(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
        liberaCampos(false);
        model_jtl_consultar_combate.setNumRows(0);
        liberaBotoes(true, false, false, false, true);
        gravar_alterar = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void pesquisa_nome_lutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_nome_lutadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_nome_lutadorActionPerformed

    
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    private void gravar() {
    try {
        lutaDTO.setNome_combate(nome_combate.getText());
        lutaDTO.setCod_combate(cod_combate.getText());
        lutaDTO.setCusto_aposta_combate(Double.parseDouble(custo_aposta_combate.getText()));
        int[] selectedRows = jtl_consultar_lutador.getSelectedRows();

        if (selectedRows.length != 2) {
            JOptionPane.showMessageDialog(null, "Selecione exatamente dois lutadores.");
            return;
        }

        int id1 = Integer.parseInt(String.valueOf(jtl_consultar_lutador.getValueAt(selectedRows[0], 0)));
        int id2 = Integer.parseInt(String.valueOf(jtl_consultar_lutador.getValueAt(selectedRows[1], 0)));

        LutadorDTO lutador1 = new LutadorDTO();
        LutadorDTO lutador2 = new LutadorDTO();

        lutador1.setId_lut(id1);
        lutador2.setId_lut(id2);

        JOptionPane.showMessageDialog(null,
            lutaCTR.inserirLuta(lutaDTO, lutador1, lutador2));

        /*lutadorDTO.setId_lut(Integer.parseInt(String.valueOf(
                jtl_consultar_lutador.getValueAt(
                jtl_consultar_lutador.getSelectedRow(), 0))));
        
        JOptionPane.showMessageDialog(null,
                lutaCTR.inserirLuta(lutaDTO, lutadorDTO, lutadorDTO));*/
    } catch (Exception e) {
        System.out.println("Erro ao Gravar: " + e.getMessage());
    }
}
    /*private void alterar() {
    try {
        lutaDTO.setNome_combate(nome_combate.getText());
        lutaDTO.setCod_combate(cod_combate.getText());
        lutaDTO.setCusto_aposta_combate(Double.parseDouble(custo_aposta_combate.getText()));
        lutadorDTO.setId_lut(Integer.parseInt(String.valueOf(
                jtl_consultar_lutador.getValueAt(
                jtl_consultar_lutador.getSelectedRow(), 0))));
        
        JOptionPane.showMessageDialog(null,
                lutaCTR.alterarLuta(lutaDTO, lutadorDTO, lutadorDTO));
    } catch (Exception e) {
        System.out.println("Erro ao Gravar: " + e.getMessage());
    }
}*/
    private void alterar() {
    try {
        lutaDTO.setNome_combate(nome_combate.getText());
        lutaDTO.setCod_combate(cod_combate.getText());
        lutaDTO.setCusto_aposta_combate(Double.parseDouble(custo_aposta_combate.getText()));

        int[] selectedRows = jtl_consultar_lutador.getSelectedRows();

        if (selectedRows.length != 2) {
            JOptionPane.showMessageDialog(null, "Selecione exatamente dois lutadores.");
            return;
        }

        int id1 = Integer.parseInt(String.valueOf(jtl_consultar_lutador.getValueAt(selectedRows[0], 0)));
        int id2 = Integer.parseInt(String.valueOf(jtl_consultar_lutador.getValueAt(selectedRows[1], 0)));

        if (id1 == id2) {
            JOptionPane.showMessageDialog(null, "Os dois lutadores devem ser diferentes.");
            return;
        }

        LutadorDTO lutador1 = new LutadorDTO();
        LutadorDTO lutador2 = new LutadorDTO();
        lutador1.setId_lut(id1);
        lutador2.setId_lut(id2);

        JOptionPane.showMessageDialog(null,
                lutaCTR.alterarLuta(lutaDTO, lutador1, lutador2));

    } catch (Exception e) {
        System.out.println("Erro ao Alterar: " + e.getMessage());
    }
}

    
    private void excluir(){
    if(JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir a Luta?", "Aviso", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,
                    lutaCTR.excluirLuta(lutaDTO));
    }
}
    
    private void liberaCampos(boolean a) {
    nome_combate.setEnabled(a);
    cod_combate.setEnabled(a);
    custo_aposta_combate.setEnabled(a);
    pesquisa_nome_lutador.setEnabled(a);
    btnPesquisarLutador.setEnabled(a);
    jtl_consultar_lutador.setEnabled(a);
}
    
    private void liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e){
    btnNovo.setEnabled(a);
    btnSalvar.setEnabled(b);
    btnCancelar.setEnabled(c);
    btnExcluir.setEnabled(d);
    btnSair.setEnabled(e);
}// fecha o método liberaBotoes
    
    private void limpaCampos() {
    nome_combate.setText("");
    cod_combate.setText("");
    custo_aposta_combate.setText("");
    pesquisa_nome_lutador.setText("");
    model_jtl_consultar_lutador.setNumRows(0);
}
    
    private void preencheTabelaCombate(String nome_combate){
    try{
        model_jtl_consultar_combate.setNumRows(0);
        lutaDTO.setNome_combate(nome_combate);
        rs = lutaCTR.consultarLuta(lutaDTO, 1);
        while(rs.next()){
            model_jtl_consultar_combate.addRow(new Object[]{
                rs.getString("id_combate"),
                rs.getString("nome_combate")
            });
        }
    }catch(Exception e){
        System.out.println("Erro ao preencheTabela"+e.getMessage());
    }finally{
        lutadorCTR.CloseDB();
    }
}

    private void preencheCamposCombate(int id_combate) {
    try {
        lutaDTO.setId_combate(id_combate);
        rs = lutaCTR.consultarLuta(lutaDTO, 2);
        if (rs.next()) {
            limpaCampos();
            nome_combate.setText(rs.getString("nome_combate"));
            cod_combate.setText(rs.getString("cod_combate"));
            custo_aposta_combate.setText(rs.getString("custo_aposta_combate"));
            
            
            model_jtl_consultar_lutador.setNumRows(0);
            model_jtl_consultar_lutador.addRow(new Object[]{
                rs.getInt("lutador1_id"),
                rs.getString("lutador1_nome")
            });
            model_jtl_consultar_lutador.addRow(new Object[]{
                rs.getInt("lutador2_id"),
                rs.getString("lutador2_nome")
            });

            jtl_consultar_lutador.setRowSelectionInterval(0, 0);
            
            gravar_alterar = 2;
            liberaCampos(true);
        }
    } catch (Exception e) {
        System.out.println("Erro ao preencheCamposProduto" + e.getMessage());
    } finally {
        lutaCTR.CloseDB();
    }
}

    private void preencheTabelaLutador(String nome_lut){
    try{
        model_jtl_consultar_lutador.setNumRows(0);
        lutadorDTO.setNome_lut(nome_lut);
        rs = lutadorCTR.consultarLutador(lutadorDTO, 1);
        while(rs.next()){
            model_jtl_consultar_lutador.addRow(new Object[]{
                rs.getString("id_lut"),
                rs.getString("nome_lut")
            });
        }
    }catch(Exception e){
        System.out.println("Erro ao preencheTabelaFornecedor"+e.getMessage());
    }finally{
        lutadorCTR.CloseDB();
    }
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnPesquisarCombate;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarLutador;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cod_combate;
    private javax.swing.JTextField custo_aposta_combate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtl_consultar_combate;
    private javax.swing.JTable jtl_consultar_lutador;
    private javax.swing.JTextField nome_combate;
    private javax.swing.JTextField pesquisa_nome_combate;
    private javax.swing.JTextField pesquisa_nome_lutador;
    // End of variables declaration//GEN-END:variables
}
